'use strict'

export * from './Auth/userAuth'
export * from './Auth/login'
export * from './OAuth/OAuth42'
export * from './OAuth/OAuthFB'
export * from './OAuth/OAuthGoogle'
export * from './OAuth/OAuthGithub'
export * from './OAuth/OAuthInstagram'
export * from './Backgrounds/backgrounds'
export * from './User/logout'
export * from './User/getUserProfile'
export * from './User/editProfile'
export * from './User/editAccount'
export * from './Movies/listMovies'
export * from './Movies/movieInfos'
export * from './Movies/searchMovies'
export * from './Movies/playMovie'
export * from './Comments/postComment'
export * from './Comments/getComments'
